export const typeLinkListData = [
  {
    type: 'shirt',
    title: 'Shirts',
    class: 'card-image__shirt',
  },
  {
    type: 'pants',
    title: 'Pants',
    class: 'card-image__pants',
  },
  {
    type: 'shoes',
    title: 'Shoes',
    class: 'card-image__shoes',
  },
];

export const allItemsTemp = [
  {
    id: 1,
    type: 'shoes',
    color: 'black',
    size: 37,
    brand: 'Tommy Hilfiger',
  },
  {
    id: 2,
    type: 'shoes',
    color: 'white',
    size: 39,
    brand: 'Calvin Klein',
  },
  {
    id: 3,
    type: 'shoes',
    color: 'red',
    size: 46,
    brand: 'GAP',
  },
  {
    id: 4,
    type: 'shoes',
    color: 'green',
    size: 43,
    brand: 'Lacoste',
  },
  {
    id: 5,
    type: 'shoes',
    color: 'pink',
    size: 37,
    brand: 'Lee Cooper',
  },
  {
    id: 6,
    type: 'shoes',
    color: 'black',
    size: 39,
    brand: 'Tommy Hilfiger',
  },
  {
    id: 7,
    type: 'shoes',
    color: 'white',
    size: 46,
    brand: 'Calvin Klein',
  },
  {
    id: 8,
    type: 'shoes',
    color: 'red',
    size: 43,
    brand: 'GAP',
  },
  {
    id: 9,
    type: 'shoes',
    color: 'green',
    size: 37,
    brand: 'Lacoste',
  },
  {
    id: 10,
    type: 'shoes',
    color: 'pink',
    size: 39,
    brand: 'Lee Cooper',
  },
  {
    id: 11,
    type: 'shoes',
    color: 'black',
    size: 45,
    brand: 'Tommy Hilfiger',
  },
  {
    id: 12,
    type: 'shoes',
    color: 'white',
    size: 46,
    brand: 'Calvin Klein',
  },
  {
    id: 13,
    type: 'shoes',
    color: 'red',
    size: 37,
    brand: 'GAP',
  },
  {
    id: 14,
    type: 'shoes',
    color: 'green',
    size: 36,
    brand: 'Lacoste',
  },
  {
    id: 15,
    type: 'shoes',
    color: 'pink',
    size: 45,
    brand: 'Lee Cooper',
  },
  {
    id: 16,
    type: 'shirt',
    color: 'black',
    size: 'S',
    brand: 'Tommy Hilfiger',
  },
  {
    id: 17,
    type: 'shirt',
    color: 'white',
    size: 'L',
    brand: 'Calvin Klein',
  },
  {
    id: 18,
    type: 'shirt',
    color: 'red',
    size: 'XL',
    brand: 'GAP',
  },
  {
    id: 19,
    type: 'shirt',
    color: 'green',
    size: 'XXL',
    brand: 'Lacoste',
  },
  {
    id: 20,
    type: 'shirt',
    color: 'pink',
    size: 'S',
    brand: 'Lee Cooper',
  },
  {
    id: 21,
    type: 'shirt',
    color: 'black',
    size: 'L',
    brand: 'Tommy Hilfiger',
  },
  {
    id: 22,
    type: 'shirt',
    color: 'white',
    size: 'XL',
    brand: 'Calvin Klein',
  },
  {
    id: 23,
    type: 'shirt',
    color: 'red',
    size: 'XXL',
    brand: 'GAP',
  },
  {
    id: 24,
    type: 'shirt',
    color: 'green',
    size: 'S',
    brand: 'Lacoste',
  },
  {
    id: 25,
    type: 'shirt',
    color: 'pink',
    size: 'L',
    brand: 'Lee Cooper',
  },
  {
    id: 26,
    type: 'shirt',
    color: 'black',
    size: 'XL',
    brand: 'Tommy Hilfiger',
  },
  {
    id: 27,
    type: 'shirt',
    color: 'white',
    size: 'XXL',
    brand: 'Calvin Klein',
  },
  {
    id: 28,
    type: 'shirt',
    color: 'red',
    size: 'S',
    brand: 'GAP',
  },
  {
    id: 29,
    type: 'shirt',
    color: 'green',
    size: 'L',
    brand: 'Lacoste',
  },
  {
    id: 30,
    type: 'shirt',
    color: 'pink',
    size: 'XL',
    brand: 'Lee Cooper',
  },
  {
    id: 31,
    type: 'pants',
    color: 'black',
    size: 36,
    brand: 'Tommy Hilfiger',
  },
  {
    id: 32,
    type: 'pants',
    color: 'white',
    size: 43,
    brand: 'Calvin Klein',
  },
  {
    id: 33,
    type: 'pants',
    color: 'red',
    size: 30,
    brand: 'GAP',
  },
  {
    id: 34,
    type: 'pants',
    color: 'green',
    size: 34,
    brand: 'Lacoste',
  },
  {
    id: 35,
    type: 'pants',
    color: 'pink',
    size: 34,
    brand: 'Lee Cooper',
  },
  {
    id: 36,
    type: 'pants',
    color: 'black',
    size: 36,
    brand: 'Tommy Hilfiger',
  },
  {
    id: 37,
    type: 'pants',
    color: 'white',
    size: 30,
    brand: 'Calvin Klein',
  },
  {
    id: 38,
    type: 'pants',
    color: 'red',
    size: 42,
    brand: 'GAP',
  },
  {
    id: 39,
    type: 'pants',
    color: 'green',
    size: 35,
    brand: 'Lacoste',
  },
  {
    id: 40,
    type: 'pants',
    color: 'pink',
    size: 39,
    brand: 'Lee Cooper',
  },
  {
    id: 41,
    type: 'pants',
    color: 'black',
    size: 48,
    brand: 'Tommy Hilfiger',
  },
  {
    id: 42,
    type: 'pants',
    color: 'white',
    size: 30,
    brand: 'Calvin Klein',
  },
  {
    id: 43,
    type: 'pants',
    color: 'red',
    size: 35,
    brand: 'GAP',
  },
  {
    id: 44,
    type: 'pants',
    color: 'green',
    size: 32,
    brand: 'Lacoste',
  },
  {
    id: 45,
    type: 'pants',
    color: 'pink',
    size: 31,
    brand: 'Lee Cooper',
  },
];
